"""initial_schema

Revision ID: 2dc105fe368d
Revises: 
Create Date: 2026-04-03 04:33:24.670360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc105fe368d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jovens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('habilitado_financeiro', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_jovens_id'), 'jovens', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=250), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jovem_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jovem_id'], ['jovens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_table('vendas_semanais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('semana_inicio', sa.Date(), nullable=False),
    sa.Column('semana_fim', sa.Date(), nullable=False),
    sa.Column('total_investido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_arrecadado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_dinheiro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('DINHEIRO', 'PIX', 'MISTO', name='metodopagamento'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_semanais_id'), 'vendas_semanais', ['id'], unique=False)
    op.create_table('ganhos_jovens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jovem_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jovem_id'], ['jovens.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas_semanais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ganhos_jovens_id'), 'ganhos_jovens', ['id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas_semanais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_ganhos_jovens_id'), table_name='ganhos_jovens')
    op.drop_table('ganhos_jovens')
    op.drop_index(op.f('ix_vendas_semanais_id'), table_name='vendas_semanais')
    op.drop_table('vendas_semanais')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_jovens_id'), table_name='jovens')
    op.drop_table('jovens')
    # ### end Alembic commands ###
