"""Remove valor_dinheiro and valor_pix from vendas_semanais

Revision ID: 58a8f8f291ac
Revises: 2f7a4e901d3a
Create Date: 2026-04-22 18:21:30.194270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a8f8f291ac'
down_revision: Union[str, None] = '2f7a4e901d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas_semanais', 'valor_pix')
    op.drop_column('vendas_semanais', 'valor_dinheiro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas_semanais', sa.Column('valor_dinheiro', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('vendas_semanais', sa.Column('valor_pix', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
