"""add evento_id to vendas_semanais

Revision ID: 8c5adb3cf5ea
Revises: merge_heads_20260415
Create Date: 2026-04-18 18:11:56.842931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5adb3cf5ea'
down_revision: Union[str, None] = 'merge_heads_20260415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas_semanais', sa.Column('evento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendas_semanais', 'eventos', ['evento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas_semanais', type_='foreignkey')
    op.drop_column('vendas_semanais', 'evento_id')
    # ### end Alembic commands ###
