"""migration_base

Revision ID: 960c223cc33e
Revises: 2dc105fe368d
Create Date: 2026-04-20 10:45:24.772192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960c223cc33e'
down_revision: Union[str, None] = '2dc105fe368d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumo_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_caixa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_dinheiro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pix', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumo_caixa_id'), 'resumo_caixa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumo_caixa_id'), table_name='resumo_caixa')
    op.drop_table('resumo_caixa')
    # ### end Alembic commands ###
