"""Permitir venda_id nulo em ganhos_jovens

Revision ID: 9674bdcd23c2
Revises: 960c223cc33e
Create Date: 2026-04-20 19:36:47.205693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9674bdcd23c2'
down_revision: Union[str, None] = '960c223cc33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ganhos_jovens', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ganhos_jovens', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
